.default_tag: &default_tag "2026-09-23.0"

build_patterns:
  - name: "meson shared expat"
    variables:
      FC_BUILDSYS: meson
      FC_BUILD_TYPE: shared
      FC_XML_BACKEND: expat
      FC_TEST_EXEC: cache-compat
      FC_BASELINE_TAG: ""
  - name: "meson shared libxml2"
    variables:
      FC_BUILDSYS: meson
      FC_BUILD_TYPE: shared
      FC_XML_BACKEND: libxml2
      FC_TEST_EXEC: meson-install-shared
  - name: "meson static libxml2 fontations"
    variables:
      FC_BUILDSYS: meson
      FC_BUILD_TYPE: static
      FC_XML_BACKEND: libxml2
      FC_BUILD_ENABLED: "fontations woff2"
      FC_TEST_EXEC: meson-install-static

test_patterns:
  - name: "subproject-build shared"
    variables:
      FC_BUILDSYS: meson
      FC_BUILD_TYPE: shared
      FC_BUILD_SUBPROJECT: 1
  - name: "subproject-build static"
    variables:
      FC_BUILDSYS: meson
      FC_BUILD_TYPE: static
      FC_BUILD_SUBPROJECT: 1
  - name: "ASAN/UBSAN"
    variables:
      FC_BUILDSYS: meson
      FC_BUILD_TYPE: shared
      FC_BUILD_ASAN: address,undefined
  - name: "TSAN"
    variables:
      FC_BUILDSYS: meson
      FC_BUILD_TYPE: shared
      FC_BUILD_ASAN: thread

distributions:
  - name: alpine
    tag: *default_tag
    base_type: alpine
    qemu_based: false
    versions:
      - "edge"
    builds:
      - name: "standard build"
        variables:
          FC_BUILDSYS: meson
          FC_BUILD_TYPE: shared
          FC_XML_BACKEND: expat
          FC_BUILD_DISABLED: nls
  - name: fedora
    tag: *default_tag
    base_type: fedora
    qemu_based: false
    versions:
      - "rawhide"
      - "45"
      - "44"
    builds:
      - name: "standard build"
        upload: "rawhide"
        doc: "rawhide"
        variables:
          FC_BUILDSYS: meson
          FC_BUILD_TYPE: shared
          FC_XML_BACKEND: libxml2
          FC_BUILD_DISTCHECK: 1
  - name: fedora
    tag: *default_tag
    base_type: fedora
    qemu_based: false
    versions:
      - "rawhide"
    builds:
      - name: "android aarch64"
        variables:
          FC_BUILDSYS: meson
          FC_BUILD_TYPE: shared
          FC_XML_BACKEND: expat
          FC_BUILD_PLATFORM: android
          FC_BUILD_ARCH: aarch64-linux-android
          FC_BUILD_NO_INSTALL: 1
          FC_BUILD_DISABLED: nls
          FC_BUILD_NO_CHECK: 1
  - name: freebsd
    tag: *default_tag
    base_type: freebsd
    qemu_based: true
    versions:
      - "14.4"
    builds:
      - name: "standard build"
        variables:
          FC_BUILDSYS: meson
          FC_BUILD_TYPE: shared
          FC_XML_BACKEND: libxml2
          FC_BUILD_NO_CHECK: 1
  - name: msys2
    tag: *default_tag
    base_type: msys2
    qemu_based: false
    versions:
      - "latest"
    builds:
      - name: "UCRT64"
        variables:
          FC_BUILDSYS: meson
          FC_BUILD_TYPE: static
          FC_XML_BACKEND: expat
          FC_BUILD_DISABLED: nls iconv
          FC_BUILD_NO_VENV: 1
          FC_BUILD_SH: msys2 -c
      - name: "MINGW64"
        variables:
          FC_BUILDSYS: meson
          FC_BUILD_TYPE: static
          FC_XML_BACKEND: expat
          FC_BUILD_DISABLED: nls iconv
          FC_BUILD_NO_VENV: 1
          FC_BUILD_SH: msys2 -c
          MSYSTEM: MINGW64

packages:
  alpine:
    needed:
      [
        "freetype-dev",
        "expat-dev",
        "python3-dev",
        "gperf",
        "util-linux-dev",
        "json-c-dev",
        "curl",
        "bash",
        "py3-pip",
        "gcc",
        "ninja-build",
        "bubblewrap",
        "pkgconf",
        "musl-dev",
        "uuidgen",
        "woff2",
        "woff2-dev",
      ]
  fedora:
    needed:
      [
        "@buildsys-build",
        "clang-devel",
        "clang-tools-extra",
        "curl",
        "gettext",
        "gettext-devel",
        "gperf",
        "expat-devel",
        "libxml2-devel",
        "freetype-devel",
        "json-c-devel",
        "git",
        "git-clang-format",
        "docbook-utils",
        "wkhtmltopdf",
        "bubblewrap",
        "ninja-build",
        "wget",
        "python3-pip",
        "rust",
        "cargo",
        "bindgen-cli",
        "libasan",
        "libtsan",
        "libubsan",
        "libabigail",
        "woff2",
        "woff2-devel",
        "woff2-tools",
      ]
  freebsd:
    needed:
      [
        "gcc",
        "gettext",
        "gperf",
        "expat",
        "libxml2",
        "freetype2",
        "json-c",
        "git",
        "wget",
        "python3",
        "py312-pip",
        "pkgconf",
        "gmake",
        "gettext-runtime",
        "ninja",
        "woff2",
      ]
  msys2:
    needed:
      [
        "git",
        "mingw-w64-ucrt-x86_64-expat",
        "mingw-w64-ucrt-x86_64-freetype",
        "mingw-w64-ucrt-x86_64-gcc",
        "mingw-w64-ucrt-x86_64-gperf",
        "mingw-w64-ucrt-x86_64-meson",
        "mingw-w64-ucrt-x86_64-python",
        "mingw-w64-ucrt-x86_64-python-certifi",
        "mingw-w64-ucrt-x86_64-python-pip",
        "mingw-w64-ucrt-x86_64-python-yaml",
        "mingw-w64-ucrt-x86_64-woff2",
        "mingw-w64-x86_64-expat",
        "mingw-w64-x86_64-freetype",
        "mingw-w64-x86_64-gcc",
        "mingw-w64-x86_64-gperf",
        "mingw-w64-x86_64-meson",
        "mingw-w64-x86_64-python",
        "mingw-w64-x86_64-python-certifi",
        "mingw-w64-x86_64-python-pip",
        "mingw-w64-x86_64-python-yaml",
        "mingw-w64-x86_64-woff2",
      ]
